# site properties and page defaults
title: Data-Cetric AI Lab
subtitle: 
description: The Data-Centric AI Lab advances state-of-the-art artificial intelligence by rethinking the role of data. Our mission is to tackle diverse challenges in areas such as computer vision, multi-modal learning, and generative AI by exploring how data can fuel advances in AI. From a data-centric standpoint, our research interests include data-efficient learning (self-supervised, weakly supervised, semi-supervised, and unsupervised learning), transfer learning, and synthetic data generation. We strive to advance AI systems that can learn effectively from limited or imperfect data, and to develop innovative methods that push the boundaries of what is possible through data-driven approaches.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: contact@DCAI-Lab.com

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
