- title: Negative-Guided Subject Fidelity Optimization for Zero-Shot Subject-Driven Generation
  authors:
    - Chaehun Shin
    - Jooyoung Choi
    - Johan Barthelemy
    - Jungbeom Lee
    - Sungroh Yoon
  publisher: arXiv
  date: 2025-06-01
  link: https://arxiv.org/abs/2506.03621
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
