- title: Negative-Guided Subject Fidelity Optimization for Zero-Shot Subject-Driven Generation
  authors:
    - Chaehun Shin
    - Jooyoung Choi
    - Johan Barthelemy
    - Jungbeom Lee
    - Sungroh Yoon
  publisher: arXiv
  date: 2025-06-01
  link: https://arxiv.org/abs/2506.03621
  # image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
- title: Know No Better: A Data-Driven Approach for Enhancing Negation Awareness in CLIP
  authors:
    - Junsung Park
    - Jungbeom Lee
    - Jongyoon Song
    - Sangwon Yu
    - Dahuin Jung
    - Sungroh Yoon
  publisher: ICCV
  date: 2025-10-15
  link: https://arxiv.org/pdf/2501.10913?

- title: Style-Friendly SNR Sampler for Style-Driven Generation
  authors:
    - Jooyoung Choi
    - Chaehun Shin
    - Yeongtak Oh
    - Heeseung Kim
    - Jungbeom Lee
    - Sungroh Yoon
  publisher: arXiv
  date: 2024-11-15
  link: https://arxiv.org/pdf/2411.14793?
