- title: Negative-Guided Subject Fidelity Optimization for Zero-Shot Subject-Driven Generation
  authors:
    - Chaehun Shin
    - Jooyoung Choi
    - Johan Barthelemy
    - Jungbeom Lee
    - Sungroh Yoon
  publisher: arXiv
  date: 2025-06-01
  link: https://arxiv.org/abs/2506.03621
